-- 전체 예약 및 사용자 데이터를 초기화
BEGIN;

TRUNCATE TABLE reservation_car_sht RESTART IDENTITY CASCADE;
TRUNCATE TABLE reservation_tour RESTART IDENTITY CASCADE;
TRUNCATE TABLE reservation_rentcar RESTART IDENTITY CASCADE;
TRUNCATE TABLE reservation_hotel RESTART IDENTITY CASCADE;
TRUNCATE TABLE reservation_airport RESTART IDENTITY CASCADE;
TRUNCATE TABLE reservation_cruise RESTART IDENTITY CASCADE;
TRUNCATE TABLE reservation RESTART IDENTITY CASCADE;

-- users 테이블은 다른 테이블에서 참조될 수 있으므로 CASCADE 여부 확인 후 사용
TRUNCATE TABLE users RESTART IDENTITY CASCADE;

COMMIT;
